const data = [
	{
		id: 1,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
	},
	{
		id: 2,
		name: "Think Manuals",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
	},
	{
		id: 3,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 4,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 5,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 6,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 7,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 8,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 9,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 10,
		name: "Reserch Assistanship",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 11,
		name: "Reserch Assistanship page2",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 12,
		name: "tests",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 13,
		name: "tests",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 14,
		name: "test",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 15,
		name: "test",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 16,
		name: "test",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 17,
		name: "test",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 18,
		name: "test",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 19,
		name: "test",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
	{
		id: 20,
		name: "test",
		image: "https://res.cloudinary.com/dtalnpahk/image/upload/v1689235193/ThinkIndia/mexsayx8ecg3yesk1kbn.jpg",
        logo: "https://res.cloudinary.com/priyojit/image/upload/v1687723646/think_india_logo_f20xsm.png",
		date: 14 ,
		month : "DEC",
    },
];

export default data;